from . import reservation
from . import livraison
from . import degradation
from . import annuler_raison
from . import reje_raison
from . import prolongation
from . import retour_avance
from . import sea_annuler_raison
from . import historique_solde
from . import book_car
from . import liste_attente
from . import contact_message
from . import condition_annumation
from . import popup_confirmation
from . import edit_reservation
