# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'reservation',
    'depends': ['base', 'liste_clients', 'gestion_du_parc', 'lieux', 'tarification'],
    'summary': "reservation des vehicules",
    'data': [
        'views/reservation_view.xml',
        'views/vehicule_inherit_view.xml',
        'views/livraison_view.xml',
        'views/liste_client_pop_up.xml',
        'views/degradation_view.xml',
        'views/annuler_raison_view.xml',
        'views/reje_raison_view.xml',
        'views/pop_up_view.xml',
        'views/prolongation_view.xml',
        'views/prolongation_pop_up.xml',
        'views/liste_client_view.xml',
        'views/liste_client_header.xml',
        'views/retour_avance_view.xml',
        'views/retour_avance_pop_up.xml',
        'views/model_optimize_planning.xml',
        'views/optimisation_planing_view.xml',
        'views/changement_restitution.xml',
        'views/sea_annuler_raison_view.xml',
        'views/historique_solde_view.xml',
        'views/book_car_view.xml',
        'views/liste_attente_views.xml',
        'views/condition_annulation_view.xml',
        'views/contact_message_view.xml',
        'views/popup_confirmation_views.xml',
        'views/edit_reservation_views.xml',
        'data/ir_cron_data.xml',
        'data/email_confirmation.xml',
        'data/email_comming_soon.xml',
        'data/email_annulation_reservation.xml',
        'data/email_retour_avance.xml',
        'data/email_livraison.xml',
        'data/email_annulation.xml',
        'data/email_non_abouti_paiement.xml',
        'data/email_prolongation_accordee.xml',
        'data/email_otp.xml',
        'data/email_google.xml',
        'data/retour.xml',
        # 'report/confirmation_pdf.xml',
        # 'report/confirmation_reservation_pdf.xml',
        'report/confirmation_reservation_pdf.xml',
        'report/contrat_pdf.xml',
        'report/nom_pdf.xml',

    ],

    'assets': {
        'web.assets_frontend': [
            'reservation/static/src/css/custom_background.css',
        ],
        'web.assets_backend': [
            'reservation/static/src/css/custom_background.css',
            'reservation/static/src/xml/kanban_xml.xml',
            'reservation/static/src/xml/kanban_agent.xml',
            'reservation/static/src/xml/kanban_reservation_xml.xml',
            'reservation/static/src/js/kanban_js.js',
            'reservation/static/src/js/kanban_agent.js',

        ],
    },
    'application': True,
}
